name: mangadex_library
description: A mangadex library for dart to facilitate easier access to the Mangadex API (https://api.mangadex.org)
version: 1.3.6
repository: https://github.com/Riktam-Santra/mangadex_library

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  http: ^0.13.3
